version: '3'

services:
  app:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.spring
    ports:
      - 8080:8080
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env.database
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db:
    driver: local